"use client";

import { useEffect, useState } from "react";
import { format, startOfMonth, endOfMonth } from "date-fns";
import { Button } from "@/components/ui/button";
import { Field, Input, Modal, Select } from "@/components/ui/primitives";
import { useFinance } from "./finance-provider";
import { financeStore } from "@/lib/finance/store";
import { budgetSchema, goalSchema } from "@/lib/finance/validation";

const first = format(startOfMonth(new Date()), "yyyy-MM-dd"), last = format(endOfMonth(new Date()), "yyyy-MM-dd");
export function BudgetDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { categories, run } = useFinance();
  const [form, setForm] = useState({ category_id: "", amount: "", starts_on: first, ends_on: last, use_custom_watch: false, budget_watch_warning_percent: "", budget_watch_critical_percent: "" });
  useEffect(() => { if (open && !form.category_id) setForm((current) => ({ ...current, category_id: categories[0]?.id ?? "" })); }, [open, form.category_id, categories]);
  const save = async () => {
    const parsed = budgetSchema.safeParse({ ...form, amount: Number(form.amount), budget_watch_warning_percent: form.use_custom_watch ? Number(form.budget_watch_warning_percent) : null, budget_watch_critical_percent: form.use_custom_watch ? Number(form.budget_watch_critical_percent) : null });
    if (!parsed.success) return;
    const result = await run(() => financeStore.saveBudget(parsed.data), "Budget created."); if (result) onClose();
  };
  return <Modal open={open} onClose={onClose} title="Set a budget"><div className="grid gap-4"><Field label="Category"><Select value={form.category_id} onChange={(event) => setForm((current) => ({ ...current, category_id: event.target.value }))}><option value="">Choose category</option>{categories.filter((category) => !category.is_archived).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></Field><Field label="Budget amount"><Input autoFocus inputMode="decimal" value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))} placeholder="0.00" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Starts"><Input type="date" value={form.starts_on} onChange={(event) => setForm((current) => ({ ...current, starts_on: event.target.value }))} /></Field><Field label="Ends"><Input type="date" value={form.ends_on} onChange={(event) => setForm((current) => ({ ...current, ends_on: event.target.value }))} /></Field></div><div className="rounded-xl border border-[var(--line)] bg-[var(--raised)] p-3"><label className="flex cursor-pointer items-center gap-2 text-sm font-medium text-[var(--text)]"><Input type="checkbox" className="h-4 w-4" checked={form.use_custom_watch} onChange={(event) => setForm((current) => ({ ...current, use_custom_watch: event.target.checked }))} />Use custom budget-watch thresholds</label><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Overrides your workspace watch thresholds for this budget only.</p>{form.use_custom_watch && <div className="mt-3 grid grid-cols-2 gap-3"><Field label="Warning %"><Input inputMode="numeric" value={form.budget_watch_warning_percent} onChange={(event) => setForm((current) => ({ ...current, budget_watch_warning_percent: event.target.value }))} placeholder="75" /></Field><Field label="Critical %"><Input inputMode="numeric" value={form.budget_watch_critical_percent} onChange={(event) => setForm((current) => ({ ...current, budget_watch_critical_percent: event.target.value }))} placeholder="90" /></Field></div>}</div><Button size="lg" onClick={save}>Create budget</Button></div></Modal>;
}
export function GoalDialog({ open, onClose }: { open: boolean; onClose: () => void }) { const { run } = useFinance(); const [form, setForm] = useState({ name: "", target_amount: "", target_date: "", color: "#C6A15A" }); const save = async () => { const parsed = goalSchema.safeParse({ ...form, target_amount: Number(form.target_amount), target_date: form.target_date || null }); if (!parsed.success) return; const result = await run(() => financeStore.saveGoal({ ...parsed.data, target_date: parsed.data.target_date ?? null }), "Savings goal created."); if (result) onClose(); }; return <Modal open={open} onClose={onClose} title="Create a savings goal"><div className="grid gap-4"><Field label="Goal name"><Input autoFocus value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} placeholder="e.g. Emergency fund" /></Field><Field label="Target amount"><Input inputMode="decimal" value={form.target_amount} onChange={(event) => setForm((current) => ({ ...current, target_amount: event.target.value }))} placeholder="0.00" /></Field><Field label="Target date" hint="Optional"><Input type="date" value={form.target_date} onChange={(event) => setForm((current) => ({ ...current, target_date: event.target.value }))} /></Field><Field label="Accent colour"><Input type="color" className="p-1" value={form.color} onChange={(event) => setForm((current) => ({ ...current, color: event.target.value }))} /></Field><p className="rounded-xl bg-[var(--raised)] px-3 py-2.5 text-xs leading-5 text-[var(--muted)]">Goal contributions track progress. Record a separate transfer if contributing money also moves it between accounts.</p><Button size="lg" onClick={save}>Create goal</Button></div></Modal>; }
export function ContributionDialog({ open, onClose, goalId, goalName }: { open: boolean; onClose: () => void; goalId: string; goalName: string }) { const { run } = useFinance(); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const save = async () => { const value = Number(amount); if (!Number.isFinite(value) || value === 0) return; const result = await run(() => financeStore.contributeToGoal(goalId, value, note), value > 0 ? "Contribution added." : "Goal withdrawal recorded."); if (result) onClose(); }; return <Modal open={open} onClose={onClose} title={`Update ${goalName}`}><div className="grid gap-4"><Field label="Amount" hint="Use a negative amount for a withdrawal"><Input autoFocus inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" /></Field><Field label="Note" hint="Optional"><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="e.g. January contribution" /></Field><Button size="lg" onClick={save}>Save goal progress</Button></div></Modal>; }
