"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, CloudSun, CreditCard, Eye, Flag, Lightbulb, Map as MapIcon, NotebookPen, Scale, ShieldCheck, Sparkles, Target, Umbrella, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, EmptyState, Input, Textarea } from "@/components/ui/primitives";
import { useFinance } from "./finance-provider";
import { annualExpenseRhythm, debtPayoffPath, decisionSimulator, financialWeather, formatMoney, leakSignals, moneyMap, monthlyReview, netWorthTrend, quietWins, spendingRhythm, summaryMetrics } from "@/lib/finance/calculations";
import { NetWorthChart, RhythmChart } from "./charts";

type JournalEntry = { id: string; createdAt: string; text: string };
type Boundary = { categoryId: string; amount: number };

function readLocal<T>(key: string, fallback: T): T {
  try { const value = window.localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; }
}

export function DiscoverScreen() {
  const { accounts, categories, settings, transactions } = useFinance();
  const currency = settings?.currency ?? "INR";
  const [purchase, setPurchase] = useState(0);
  const [note, setNote] = useState("");
  const [notes, setNotes] = useState<JournalEntry[]>([]);
  const [boundary, setBoundary] = useState<Boundary | null>(null);
  const [hydrated, setHydrated] = useState(false);
  const metrics = useMemo(() => summaryMetrics(accounts, transactions, settings), [accounts, transactions, settings]);
  const weather = useMemo(() => financialWeather(accounts, transactions, settings), [accounts, transactions, settings]);
  const review = useMemo(() => monthlyReview(transactions, categories), [transactions, categories]);
  const decision = useMemo(() => decisionSimulator(purchase, accounts, transactions, settings), [purchase, accounts, transactions, settings]);
  const netWorth = useMemo(() => netWorthTrend(accounts, transactions), [accounts, transactions]);
  const rhythm = useMemo(() => spendingRhythm(transactions), [transactions]);
  const annual = useMemo(() => annualExpenseRhythm(transactions), [transactions]);
  const flow = useMemo(() => moneyMap(transactions, categories), [transactions, categories]);
  const leaks = useMemo(() => leakSignals(transactions), [transactions]);
  const wins = useMemo(() => quietWins(accounts, transactions, categories, settings), [accounts, transactions, categories, settings]);
  const debtPath = useMemo(() => debtPayoffPath(accounts, transactions), [accounts, transactions]);
  const categoryNames = useMemo(() => new Map(categories.map((category) => [category.id, category.name])), [categories]);
  const boundarySpent = boundary ? transactions.filter((transaction) => transaction.type === "expense" && transaction.category_id === boundary.categoryId && transaction.transaction_date.slice(0, 7) === new Date().toISOString().slice(0, 7)).reduce((total, transaction) => total + Number(transaction.amount), 0) : 0;
  const peakMonth = [...annual].sort((a, b) => b.expense - a.expense)[0];

  useEffect(() => { setNotes(readLocal<JournalEntry[]>("finwise:journal", [])); setBoundary(readLocal<Boundary | null>("finwise:boundary", null)); setHydrated(true); }, []);
  const saveNote = () => { const text = note.trim(); if (!text) return; const next = [{ id: crypto.randomUUID(), createdAt: new Date().toISOString(), text }, ...notes].slice(0, 12); setNotes(next); window.localStorage.setItem("finwise:journal", JSON.stringify(next)); setNote(""); };
  const saveBoundary = (categoryId: string, amount: number) => { const next = categoryId && amount > 0 ? { categoryId, amount } : null; setBoundary(next); window.localStorage.setItem("finwise:boundary", JSON.stringify(next)); };

  return <div className="grid gap-7">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-[var(--accent)]">Discover</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight">A clearer story behind your money.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Every signal below is derived from your recorded ledger and preferences. Nothing here moves money, changes a category, or makes a decision for you.</p></div><div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] px-4 py-3"><p className="text-xs text-[var(--muted)]">Financial weather</p><div className="mt-1 flex items-center gap-2"><CloudSun size={18} className={weather.state === "clear" ? "text-emerald-400" : weather.state === "tight" ? "text-[#f6a18b]" : "text-[var(--accent)]"} /><p className="font-medium">{weather.label}</p></div></div></div>

    <Card className="overflow-hidden p-0"><div className="grid gap-5 p-5 sm:p-6 lg:grid-cols-[.78fr_1.22fr]"><div><div className="flex items-center gap-2 text-[var(--accent)]"><Sparkles size={17} /><p className="text-xs font-medium uppercase tracking-[.16em]">Your next 30 days</p></div><h2 className="mt-3 font-display text-2xl font-semibold">{weather.message}</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Safe to Spend today is <span className="font-mono text-[var(--ink)]">{formatMoney(metrics.safeToSpend, currency)}</span>. It already keeps your reserve target and commitments outside everyday spending room.</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[var(--raised)] p-4"><p className="text-xs text-[var(--muted)]">This month in</p><p className="mt-2 font-mono text-lg font-medium">{formatMoney(review.currentIncome, currency)}</p></div><div className="rounded-2xl bg-[var(--raised)] p-4"><p className="text-xs text-[var(--muted)]">This month out</p><p className="mt-2 font-mono text-lg font-medium">{formatMoney(review.currentSpending, currency)}</p></div><div className="rounded-2xl bg-[var(--raised)] p-4"><p className="text-xs text-[var(--muted)]">Monthly rhythm</p><p className="mt-2 font-mono text-lg font-medium">{review.savingsRate === null ? "—" : `${Math.round(review.savingsRate)}%`}</p></div></div></div></Card>

    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Scale size={18} className="text-emerald-400" /><h2 className="font-display text-lg font-semibold">Financial altitude</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Month-end net worth from active account opening balances and recorded ledger activity.</p></div><p className="font-mono text-sm text-[var(--muted)]">{formatMoney(netWorth.at(-1)?.netWorth ?? 0, currency)}</p></div><div className="mt-4"><NetWorthChart data={netWorth} currency={currency} /></div></Card>
      <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><MapIcon size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Money map</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">A simple read of how this month’s recorded income is flowing.</p><div className="mt-5 grid gap-3"><FlowRow label="Income" value={flow.income} currency={currency} tone="positive" /><FlowRow label="Needs" value={flow.essential} currency={currency} /><FlowRow label="Flexible spending" value={flow.flexible} currency={currency} /><FlowRow label="Still unallocated" value={flow.net} currency={currency} tone={flow.net >= 0 ? "positive" : "negative"} /></div>{flow.top.length ? <div className="mt-5 border-t border-[var(--line)] pt-4"><p className="text-xs text-[var(--muted)]">Largest recorded categories</p><div className="mt-2 flex flex-wrap gap-2">{flow.top.map((item) => <span key={item.name} className="rounded-full bg-[var(--raised)] px-2.5 py-1 text-xs">{item.name} · {formatMoney(item.value, currency, true)}</span>)}</div></div> : null}</Card></div>

    <Card className="p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><CreditCard size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Debt payoff path</h2></div><p className="mt-1 max-w-2xl text-xs leading-5 text-[var(--muted)]">Current credit-account balances and this month’s recorded repayments. Finwise does not estimate interest or a payoff date until you choose to add those details.</p></div>{debtPath.length ? <p className="font-mono text-sm text-[var(--muted)]">{formatMoney(debtPath.reduce((total, item) => total + item.balance, 0), currency)} outstanding</p> : null}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{debtPath.length ? debtPath.map((item) => <div key={item.accountId} className="rounded-2xl bg-[var(--raised)] p-4"><p className="text-sm font-medium">{item.accountName}</p><p className="mt-2 font-mono text-lg">{formatMoney(item.balance, currency)}</p><p className="mt-2 text-xs text-[var(--muted)]">{item.recordedRepaymentsThisMonth > 0 ? `${formatMoney(item.recordedRepaymentsThisMonth, currency)} repaid this month` : "No repayment recorded this month"}</p></div>) : <EmptyState title="No active credit balance" description="When a credit account carries a recorded balance, its payoff context will appear here." />}</div></Card>

    <div className="grid gap-5 xl:grid-cols-[.95fr_1.05fr]"><Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Target size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Decision simulator</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Try a purchase before recording it. This is a private calculation, not a transaction.</p><label className="mt-5 block text-xs font-medium text-[var(--muted)]">Proposed purchase <Input className="mt-2 h-11 font-mono" min="0" type="number" value={purchase || ""} onChange={(event) => setPurchase(Number(event.target.value))} placeholder="0" /></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[var(--raised)] p-3"><p className="text-xs text-[var(--muted)]">After purchase</p><p className={`mt-1 font-mono text-lg ${decision.afterPurchase < 0 ? "text-[#f6a18b]" : "text-[var(--ink)]"}`}>{formatMoney(decision.afterPurchase, currency)}</p></div><div className="rounded-2xl bg-[var(--raised)] p-3"><p className="text-xs text-[var(--muted)]">After recorded bills</p><p className={`mt-1 font-mono text-lg ${decision.afterBills < 0 ? "text-[#f6a18b]" : "text-[var(--ink)]"}`}>{formatMoney(decision.afterBills, currency)}</p></div></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{decision.cost <= 0 ? "Enter an amount to compare it with your current flexible room." : decision.state === "comfortable" ? "Comfortable within the current ledger-based plan. You still decide whether it matters." : decision.state === "watch" ? "Possible, but recorded upcoming bills make the margin tighter." : "This would exceed today’s protected Safe to Spend. Consider waiting, lowering the amount, or changing the plan."}</p>{decision.cost > 0 && metrics.safeToSpend > 0 ? <p className="mt-2 text-xs text-[var(--muted)]">True-cost lens: {Math.round((decision.cost / metrics.safeToSpend) * 100)}% of today’s flexible spending room.</p> : null}</Card>
      <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Eye size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">What changed?</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">A concise, explainable monthly review—not a scorecard.</p><div className="mt-5 grid gap-3">{review.currentSpending || review.currentIncome ? <><InsightRow icon={review.spendingChange > 0 ? <ArrowUpRight size={15} /> : <ArrowDownRight size={15} />} title={`Spending is ${review.direction}`} body={review.spendingChange === 0 ? "Recorded spending is similar to last month so far." : `${formatMoney(Math.abs(review.spendingChange), currency)} ${review.spendingChange > 0 ? "more" : "less"} than last month so far.`} tone={review.spendingChange > 0 ? "caution" : "positive"} />{review.topCategory ? <InsightRow icon={<WalletCards size={15} />} title={`${review.topCategory.name} is currently largest`} body={`${formatMoney(review.topCategory.value, currency)} of recorded spending this month.`} /> : null}{review.emergingCategory ? <InsightRow icon={<Lightbulb size={15} />} title={`${review.emergingCategory.name} is moving`} body={`${formatMoney(review.emergingCategory.increase, currency)} higher than last month so far.`} /> : null}</> : <EmptyState title="No monthly story yet" description="Record income and expenses to see an explainable month-to-date review." />}</div></Card></div>

    <div className="grid gap-5 xl:grid-cols-2"><Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Umbrella size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Spending rhythm</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">A three-month average of when spending tends to accelerate. Use it to plan before the pressure point.</p><div className="mt-4"><RhythmChart data={rhythm} currency={currency} /></div></Card><Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Flag size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Annual rhythm</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Seasonal context from the last twelve recorded months—not a prediction.</p><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-6">{annual.map((month) => <div key={month.label} className="rounded-xl bg-[var(--raised)] p-2.5"><p className="text-xs text-[var(--muted)]">{month.label}</p><p className="mt-1 font-mono text-xs">{formatMoney(month.expense, currency, true)}</p></div>)}</div>{peakMonth?.expense ? <p className="mt-4 text-sm leading-6 text-[var(--muted)]">Your most expensive recorded month in this view was <span className="font-medium text-[var(--ink)]">{peakMonth.label}</span>. Use this only as a preparation cue for the next similar season.</p> : null}</Card></div>

    <div className="grid gap-5 xl:grid-cols-[.88fr_1.12fr]"><Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Gentle boundary</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Set a private, device-only intention for one category. It never blocks a transaction.</p><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_.7fr]"><select aria-label="Boundary category" className="h-11 rounded-xl border border-[var(--line)] bg-[var(--raised)] px-3 text-sm" defaultValue={boundary?.categoryId ?? ""} onChange={(event) => saveBoundary(event.target.value, boundary?.amount ?? 0)}><option value="">Choose a category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><Input aria-label="Boundary amount" className="h-11 font-mono" min="0" type="number" defaultValue={boundary?.amount ?? ""} onBlur={(event) => saveBoundary(boundary?.categoryId ?? "", Number(event.target.value))} placeholder="Amount" /></div>{hydrated && boundary ? <div className="mt-4 rounded-2xl bg-[var(--raised)] p-3"><p className="text-xs text-[var(--muted)]">{categoryNames.get(boundary.categoryId) ?? "Category"} this month</p><p className="mt-1 font-mono text-lg">{formatMoney(boundarySpent, currency)} <span className="text-sm text-[var(--muted)]">of {formatMoney(boundary.amount, currency)}</span></p><p className={`mt-2 text-xs ${boundarySpent > boundary.amount ? "text-[#f6a18b]" : "text-[var(--muted)]"}`}>{boundarySpent > boundary.amount ? "Past your chosen boundary. This is information, not a failure." : `${formatMoney(Math.max(0, boundary.amount - boundarySpent), currency)} remains in this gentle boundary.`}</p></div> : null}</Card>
      <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><NotebookPen size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Financial journal</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Private context for a chart or month—kept only in this browser unless you choose to export it separately.</p><Textarea className="mt-4 min-h-24" value={note} onChange={(event) => setNote(event.target.value)} placeholder="For example: moved homes, changed jobs, or had a one-off medical expense." /><Button className="mt-3" size="sm" type="button" onClick={saveNote}>Save private note</Button>{hydrated && notes.length ? <div className="mt-5 grid gap-2">{notes.slice(0, 3).map((entry) => <div key={entry.id} className="rounded-xl bg-[var(--raised)] px-3 py-2.5"><p className="text-sm leading-5">{entry.text}</p><p className="mt-1 text-xs text-[var(--muted)]">{new Date(entry.createdAt).toLocaleDateString()}</p></div>)}</div> : null}</Card></div>

    <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Lightbulb size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Quiet wins</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Meaningful progress that can be easy to overlook.</p><div className="mt-5 grid gap-2">{wins.length ? wins.map((win) => <div key={win} className="rounded-xl bg-emerald-500/10 px-3 py-3 text-sm leading-6 text-emerald-100">{win}</div>) : <EmptyState title="Your wins will surface here" description="As ledger patterns develop, Finwise will point out sustained progress without turning it into a score." />}</div></Card><Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[var(--accent)]" /><h2 className="font-display text-lg font-semibold">Patterns worth checking</h2></div><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Repeated recorded expenses are surfaced for your review. They are not cancelled or classified automatically.</p><div className="mt-5 grid gap-2">{leaks.length ? leaks.map((signal) => <div key={signal.description} className="flex items-center justify-between gap-3 rounded-xl bg-[var(--raised)] px-3 py-3"><div><p className="text-sm font-medium capitalize">{signal.description}</p><p className="mt-1 text-xs text-[var(--muted)]">{signal.records.length} recorded payments in the last three months</p></div><p className="font-mono text-sm">{formatMoney(signal.average, currency)}</p></div>) : <EmptyState title="No repeat pattern yet" description="Once the ledger contains repeated descriptions, patterns will appear here for a human review." />}</div></Card></div>
  </div>;
}

function FlowRow({ label, value, currency, tone }: { label: string; value: number; currency: string; tone?: "positive" | "negative" }) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-[var(--raised)] px-3.5 py-3"><p className="text-sm text-[var(--muted)]">{label}</p><p className={`font-mono text-sm ${tone === "positive" ? "text-emerald-400" : tone === "negative" ? "text-[#f6a18b]" : "text-[var(--ink)]"}`}>{formatMoney(value, currency)}</p></div>; }
function InsightRow({ body, icon, title, tone }: { body: string; icon: React.ReactNode; title: string; tone?: "positive" | "caution" }) { return <div className="flex gap-3 rounded-xl bg-[var(--raised)] p-3"><div className={`mt-0.5 ${tone === "positive" ? "text-emerald-400" : tone === "caution" ? "text-[var(--accent)]" : "text-[var(--muted)]"}`}>{icon}</div><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{body}</p></div></div>; }
