"use client";

import { type InputHTMLAttributes, type ReactNode, useEffect } from "react";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";

export function Card({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn("rounded-2xl border border-[var(--line)] bg-[var(--panel)] shadow-panel", className)}>{children}</section>; }
export function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-[var(--ink)]"><span>{label}</span>{children}{hint && <span className="text-xs font-normal text-[var(--muted)]">{hint}</span>}</label>; }
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-10 w-full rounded-xl border border-[var(--line)] bg-[var(--field)] px-3 text-sm text-[var(--ink)] outline-none placeholder:text-[var(--muted)] focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]", className)} {...props} />; }
export function Select({ className, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn("h-10 w-full rounded-xl border border-[var(--line)] bg-[var(--field)] px-3 text-sm text-[var(--ink)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]", className)} {...props}>{children}</select>; }
export function Textarea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("min-h-20 w-full rounded-xl border border-[var(--line)] bg-[var(--field)] px-3 py-2.5 text-sm text-[var(--ink)] outline-none placeholder:text-[var(--muted)] focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]", className)} {...props} />; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="flex min-h-56 flex-col items-center justify-center px-6 py-10 text-center"><div className="mb-4 grid h-11 w-11 place-items-center rounded-2xl bg-[var(--raised)] text-xl">+</div><h3 className="font-display text-lg font-semibold text-[var(--ink)]">{title}</h3><p className="mt-1 max-w-sm text-sm leading-6 text-[var(--muted)]">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function Modal({ open, onClose, title, children, wide = false }: { open: boolean; onClose: () => void; title: string; children: ReactNode; wide?: boolean }) {
  useEffect(() => { if (!open) return; const listener = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/55 p-0 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-label={title}><div className={cn("max-h-[92vh] w-full overflow-y-auto rounded-t-3xl border border-[var(--line)] bg-[var(--panel)] p-5 shadow-float sm:rounded-3xl sm:p-7", wide ? "max-w-3xl" : "max-w-lg")}><div className="mb-5 flex items-center justify-between gap-4"><h2 className="font-display text-xl font-semibold text-[var(--ink)]">{title}</h2><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl text-[var(--muted)] hover:bg-[var(--raised)] hover:text-[var(--ink)]"><X size={18} /></button></div>{children}</div></div>;
}
export function Segmented({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <div className="inline-flex rounded-xl bg-[var(--raised)] p-1">{options.map((option) => <button key={option.value} onClick={() => onChange(option.value)} className={cn("rounded-lg px-3 py-1.5 text-xs font-medium transition", value === option.value ? "bg-[var(--panel)] text-[var(--ink)] shadow-sm" : "text-[var(--muted)] hover:text-[var(--ink)]")}>{option.label}</button>)}</div>; }
